services:
  php:
    build:
      context: docker/php
      target: php
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/.composer/cache
      - ~/.composer/auth.json:/.composer/auth.json
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - COMPOSER_HOME=/.composer
      - XDG_CONFIG_HOME=/tmp/.config
    depends_on:
      - db
      - redis
      - mail

  php-debug:
    build:
      context: docker/php
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/.composer/cache
      - ~/.composer/auth.json:/.composer/auth.json
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}
      - COMPOSER_HOME=/.composer
      - XDG_CONFIG_HOME=/tmp/.config
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db
      - redis
      - mail

  web:
    build:
      context: docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - 8080:443
    depends_on:
      - php
      - php-debug

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DATABASE=laravel

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redisinsights:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsights-data:/data

  mail:
    image: axllent/mailpit:v1.10
    ports:
      - 8025:8025

  # composer:
  #   build:
  #     context: docker/php
  #   user: "${UID:-1000}:${GID:-1000}"
  #   volumes:
  #     - ./src:/var/www/html
  #   entrypoint: composer
  #   depends_on:
  #     - php
  #   profiles:
  #     - cli

  # artisan:
  #   build:
  #     context: docker/php
  #   user: "${UID:-1000}:${GID:-1000}"
  #   entrypoint: ["php", "/var/www/html/artisan"]
  #   volumes:
  #     - ./src:/var/www/html
  #   depends_on:
  #     - db
  #   profiles:
  #     - cli

volumes:
  pg-data:
  redis-data:
  redisinsights-data:
